commonLabels:
  app: redis
  comp: sentinel
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: sentinel-auth
  files:
  - sentinel.conf
secretGenerator:
- name: sentinel-auth
  literals:
  - SENTINEL_PASSWORD=secret
