apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    comp: broker
spec:
  selector:
    comp: broker
  ports:
  - name: server
    port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    comp: broker
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    comp: broker
  ports:
  - name: server
    port: 9092
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka
  labels:
    comp: broker
spec:
  selector:
    matchLabels:
      comp: broker
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    comp: broker
spec:
  selector:
    matchLabels:
      comp: broker
  serviceName: kafka-headless
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: datadir
      labels:
        comp: broker
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        comp: broker
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                comp: broker
            topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zk
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: config
        configMap:
          name: kafka
      containers:
      - name: broker
        imagePullPolicy: Always
        image: registry.local/santhoshkt/kafka:2.5.0
        ports:
        - name: server
          containerPort: 9092
        env:
        - name: KAFKA_HEAP_OPTS
          value: -Xmx512M -Xms512M
        command:
        - bash
        - -c
        - |
          set -e
          HOST=$(hostname -s)
          DOMAIN=$(hostname -d)
          if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
              NAME=${BASH_REMATCH[1]}
              ORD=${BASH_REMATCH[2]}
          else
              echo "Failed to parse hostname $HOST"
              exit 1
          fi
          cp /configtmp/server.properties config/server.properties
          sed -i -e "s/\${BROKER_ID}/$((ORD+1))/g" \
                 -e "s/\${HOSTNAME}/$HOST.$DOMAIN/g" config/server.properties
          exec "$@"
        - --
        args:
        - kafka-server-start.sh
        - config/server.properties
        volumeMounts:
        - name: config
          mountPath: /configtmp
        - name: datadir
          mountPath: /data
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          exec:
            command: [ "kafka-broker-api-versions.sh", "--bootstrap-server=localhost:9092" ]
