apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-create-topics
        image: registry.local/santhoshkt/kafka:2.5.0
        command:
        - bash
        - -c
        - |
          set -e
          for arg in "$@"; do
              IFS=':' read -r -a opt <<< "$arg"
              cmd="/kafka/bin/kafka-topics.sh --create --if-not-exists --zookeeper=zk:2181 --topic=${opt[0]} --partitions=${opt[1]} --replication-factor=${opt[2]}"
              for config in "${opt[@]:3}"; do
                  cmd="$cmd --config=$config"
              done
              echo + $cmd
              until $cmd; do
                  sleep 10
                  echo retrying...
              done
          done
        args:
          - --
          - test1:1:3:cleanup.policy=compact
          - test2:1:3:cleanup.policy=compact:compression.type=gzip
          - test3:1:3
