commonLabels:
  app: kafka
  comp: broker
configMapGenerator:
- name: kafka
  files:
  - config/server.properties
  - config/log4j.properties
resources:
- statefulset.yaml
- service.yaml
- create-topics.yaml
