apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    comp: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      comp: metrics
  template:
    metadata:
      labels:
        comp: metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      containers:
      - name: metrics-exporter
        image: danielqsj/kafka-exporter:v1.2.0
        ports:
        - name: http
          containerPort: 9308