apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  publishNotReadyAddresses: true
  selector:
    app: kafka
  clusterIP: None
  ports:
  - name: server
    port: 9092
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headess
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kafka
            topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zk
              topologyKey: kubernetes.io/hostname
      volumes:
      - name: config
        configMap:
          name: kafka-config
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: registry.local/santhoshkt/kafka:2.5.0
        ports:
        - name: server
          containerPort: 9092
        env:
        - name: KAFKA_HEAP_OPTS
          value: -Xmx512M -Xms512M
        volumeMounts:
        - name: config
          mountPath: /config
        - name: datadir
          mountPath: /data
        readinessProbe:
          exec:
            command: [ "/kafka_2.12-2.5.0/bin/kafka-broker-api-versions.sh", "--bootstrap-server=localhost:9092" ]
          initialDelaySeconds: 10
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
