commonLabels:
  app: redis
  comp: server
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: redis-auth
  files:
  - redis.conf
secretGenerator:
- name: redis-auth
  literals:
  - REDIS_PASSWORD=secret
  - SENTINEL_USER=sentinel
  - SENTINEL_PASSWORD=U6FP4PBA0r
