commonLabels:
  app: elasticsearch
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: elasticsearch-auth
  literals:
  - ELASTIC_PASSWORD=secret
configMapGenerator:
- name: elasticsearch-auth
  literals:
  - xpack.security.enabled=true
