commonLabels:
  app: redis
  comp: sentinel
configMapGenerator:
- name: sentinel
  files:
  - sentinel.conf
secretGenerator:
- name: sentinel
  literals:
  - SENTINEL_PASSWORD=secret
  - REDIS_USER=sentinel
  - REDIS_PASSWORD=U6FP4PBA0r
resources:
- service.yaml
- statefulset.yaml
