commonLabels:
  app: redis
  comp: sentinel
configMapGenerator:
- name: sentinel
  files:
  - sentinel.conf
secretGenerator:
- name: sentinel
  literals:
  - PASSWORD=secret
resources:
- service.yaml
- statefulset.yaml
