commonLabels:
  app: redis
  comp: sentinel
configMapGenerator:
- name: sentinel
  files:
  - sentinel.conf
secretGenerator:
- name: sentinel
  literals:
  - SENTINEL_PASSWORD=secret
  - REDIS_USER=root
  - REDIS_PASSWORD=secret
resources:
- service.yaml
- statefulset.yaml
