commonLabels:
  app: redis
  comp: sentinel
configMapGenerator:
- name: sentinel
  files:
  - sentinel.conf
  - redis-auth.conf
secretGenerator:
- name: sentinel
  literals:
  - SENTINEL_PASSWORD=secret
resources:
- service.yaml
- statefulset.yaml
