apiVersion: v1
kind: Service
metadata:
  name: sentinel-0
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-0
  ports:
  - name: client
    port: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-1
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-1
  ports:
  - name: client
    port: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-2
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: sentinel-2
  ports:
  - name: client
    port: 26379
