scrape_configs:
- job_name: kube-controller-manager
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_tier, __meta_kubernetes_service_label_component]
    regex: kube-system;control-plane;kube-controller-manager
    action: keep
