apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    component: kube-controller-manager
    tier: control-plane
spec:
  selector:
    component: kube-controller-manager
    tier: control-plane
  ports:
  - name: http-metrics
    port: 10252
