namespace: prometheus
commonLabels:
  app: prometheus
  comp: blackbox-exporter
configMapGenerator:
- name: prometheus-blackbox-exporter
  files:
  - blackbox.yml
resources:
- deployment.yaml
- service.yaml
