apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager-headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-alertmanager
spec:
  serviceName: prometheus-alertmanager-headless
  replicas: 1
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 2Gi
  template:
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
      volumes:
      - name: config
        configMap:
          name: prometheus-alertmanager
      containers:
      - name: prometheus-alertmanager
        image: prom/alertmanager:v0.20.0
        ports:
        - name: http
          containerPort: 9093
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: datadir
          mountPath: /alertmanager
        args:
        - --config.file=/etc/alertmanager/alertmanager.yml
        - --storage.path=/alertmanager
        - --web.external-url=http://localhost:9093
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 30
          httpGet:
            path: /#/status
            port: 9093
