commonLabels:
  app: cassandra
configMapGenerator:
- name: cassandra
  files:
  - cassandra.yaml
  - cassandra-rackdc.properties
  - initialize.cql
secretGenerator:
- name: cassandra
  literals:
  - CASSANDRA_PASSWORD=secret
resources:
- statefulset.yaml
- initialize.yaml
