namespace: kube-system # should match the namespace in prometheus.yml/alerting.alertmanagers.relabel_configs.regex
commonLabels:
  app: prometheus
configMapGenerator:
- name: prometheus-server
  files:
  - prometheus.yml
  - recording_rules.yml
  - alerting_rules.yml
- name: prometheus-alertmanager
  files:
  - alertmanager.yml
- name: prometheus-blackbox-exporter
  files:
  - blackbox.yml
resources:
  - alertmanager.yaml
  - blackbox-exporter.yaml
  - node-exporter.yaml
  - kube-scheduler.yaml
  - server.yaml
