apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  labels:
    comp: node-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    comp: node-exporter
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  labels:
    comp: node-exporter
spec:
  selector:
    matchLabels:
      comp: node-exporter
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        comp: node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      containers:
      - name: prometheus-node-exporter
        image: prom/node-exporter:v0.18.1
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly:  true
        - name: sys
          mountPath: /host/sys
          readOnly: true
