apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: tls
        secret:
          secretName: kibana-tls
          optional: true
      - name: elasticsearch-tls
        secret:
          secretName: elasticsearch-tls
          optional: true
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: docker.elastic.co/kibana/kibana:7.6.2
        ports:
        - name: http
          containerPort: 5601
        envFrom:
        - secretRef:
            name: kibana
            optional: true
        - configMapRef:
            name: kibana-tls
            optional: true
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: NODE_OPTIONS
          value: --max-old-space-size=1800
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-auth
              key: ELASTIC_PASSWORD
              optional: true
        - name: ELASTIC_TLS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-tls
              key: xpack.security.http.ssl.enabled
              optional: true
        args:
        - bash
        - -ce
        - |
          if [ "$ELASTIC_TLS_ENABLED" = "true" ]; then
              export ELASTICSEARCH_HOSTS=https${ELASTICSEARCH_HOSTS#http}
              export ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/elasticsearch-tls/tls.crt
              export ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
          fi
          exec /usr/local/bin/kibana-docker
        volumeMounts:
        - name: tls
          mountPath: /tls
        - name: elasticsearch-tls
          mountPath: /elasticsearch-tls
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -ce
            - |
              if [ -n "$ELASTICSEARCH_USERNAME" ] && [ -n "$ELASTICSEARCH_PASSWORD" ]; then
                auth="-u $ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD"
              fi
              if [ "$SERVER_SSL_ENABLED" = "true" ]; then
                  protocol=https
              else
                  protocol=http
              fi
              curl -ksSfL $auth $protocol://127.0.0.1:5601/app/kibana --output /dev/null
