apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: kibana
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        image: docker.elastic.co/kibana/kibana:7.6.2
        ports:
        - name: http
          containerPort: 5601
        envFrom:
        - secretRef:
            name: kibana
            optional: true
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://es:9200
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: NODE_OPTIONS
          value: --max-old-space-size=1800
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -ce
            - |
              if [ -n "$ELASTICSEARCH_USERNAME" ] && [ -n "$ELASTICSEARCH_PASSWORD" ]; then
                auth="-u $ELASTICSEARCH_USERNAME:$ELASTICSEARCH_PASSWORD"
              fi
              curl -sSfL $auth 127.0.0.1:5601/app/kibana --output /dev/null
