apiVersion: v1
kind: Service
metadata:
  name: zk-headless
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: peer
    port: 2888
  - name: election
    port: 3888
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  selector:
    matchLabels: {}
  minAvailable: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-headless
  replicas: 3
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7000"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 180
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {}
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: config
        configMap:
          name: zk-config
      containers:
      - name: zk
        imagePullPolicy: Always
        image: registry.local/santhoshkt/zookeeper:3.6.1
        ports:
        - name: peer
          containerPort: 2888
        - name: election
          containerPort: 3888
        - name: client
          containerPort: 2181
        - name: metrics
          containerPort: 7000
        env:
        - name: REPLICAS
          value: "3" # should match Statefulset.spec.replicas
        - name: ZK_SERVER_HEAP
          value: "1024" # jvm heapsize in mb
        volumeMounts:
        - name: config
          mountPath: /zookeeper/conf/zoo.cfg
          subPath: zoo.cfg
        - name: datadir
          mountPath: /zookeeper/data
        readinessProbe:
          exec:
            command: [ "zkOk.sh" ]
          initialDelaySeconds: 10
          timeoutSeconds: 5
