scrape_configs:
- job_name: node-exporter
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    regex: node-exporter
    action: keep
  - source_labels: [__meta_kubernetes_pod_node_name]
    target_label: instance
    action: replace
