namespace: monitoring
commonLabels:
  app: prometheus
configMapGenerator:
- name: prometheus
  files:
  - prometheus.yml
  - recording_rules.yml
  - alerting_rules.yml
resources:
- rbac.yaml
- statefulset.yaml
- service.yaml
