apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: epmd
    port: 4369
  - name: amqp
    port: 5672
  - name: amqps
    port: 5671
  - name: dist
    port: 25672
  - name: http
    port: 15672
  - name: https
    port: 15671
