apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      containers:
      - name: exporter
        image: danielqsj/kafka-exporter:v1.2.0
        ports:
        - name: http
          containerPort: 9308
