apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: LoadBalancer
  loadBalancerIP: 172.28.128.250
  selector:
    app: registry
  ports:
  - name: https
    port: 443
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      - name: tls
        secret:
          secretName: tls-secret
      containers:
      - name: registry
        image: registry:2
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /var/lib/registry 
        - name: tls
          mountPath: /certs
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:443
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
