scrape_configs:
- job_name: kube-state-metrics
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app]
    regex: monitoring;kube-state-metrics
    action: keep
