apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  selector:
    component: kube-scheduler
    tier: control-plane
  ports:
  - name: http-metrics
    port: 10251
