namespace: prometheus
commonLabels:
  app: prometheus
  comp: server
configMapGenerator:
- name: prometheus-server
  files:
  - prometheus.yml
  - recording_rules.yml
  - alerting_rules.yml
resources:
- rbac.yaml
- statefulset.yaml
- service.yaml
