namespace: kube-system # should match the namespace in prometheus.yml/alerting.alertmanagers.relabel_configs.regex
commonLabels:
  app: prometheus
  comp: server
configMapGenerator:
- name: prometheus-server
  files:
  - prometheus.yml
  - recording_rules.yml
  - alerting_rules.yml
resources:
- rbac.yaml
- statefulset.yaml
- service.yaml
