apiVersion: v1
kind: Service
metadata:
  name: redis-0
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-0
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-1
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-1
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-2
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-2
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-3
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-3
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-4
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-4
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-5
spec:
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: redis-5
  ports:
  - name: client
    port: 6379
  - name: bus
    port: 16379
